# Generated by Django 4.2.3 on 2023-08-17 18:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('_quantity', models.FloatField(default=0)),
                ('_buy_price', models.FloatField()),
                ('buy_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shares_type', models.CharField(choices=[('SHR', 'Share'), ('ETF', 'ETF')], max_length=5)),
                ('market', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=100)),
                ('dividend_yield', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('_quantity', models.FloatField(default=0)),
                ('_buy_price', models.FloatField()),
                ('buy_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gold_type', models.CharField(choices=[('BC', 'Bullion Coin'), ('GB', 'Gold Bar'), ('CT', 'Contract')], max_length=2)),
                ('origin', models.CharField(max_length=30)),
                ('fineness', models.PositiveIntegerField(default=999, validators=[django.core.validators.MaxValueValidator(999)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('PLN', 'Polish Zloty'), ('USD', 'United States Dolar'), ('EUR', 'Euro'), ('GBP', 'Great British Pound'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan Renminbi'), ('JPY', 'Japanese Yen')], max_length=3)),
                ('ballance', models.FloatField(default=0)),
                ('main_currency', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('_quantity', models.FloatField(default=0)),
                ('_buy_price', models.FloatField()),
                ('buy_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage_place', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
