# Generated by Django 4.2.3 on 2023-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLN_ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('USD', 'United States Dolar'), ('EUR', 'Euro'), ('GBP', 'Great British Pound'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan Renminbi'), ('JPY', 'Japanese Yen')], max_length=3)),
                ('exchange_rate', models.FloatField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
